interface EmailData {
    subject?: string;
    sender?: string;
    body: string;
}

export const generateSummary = async (
    email: EmailData
): Promise<string> => {
    console.log("Email received by AI service:");
    console.log(email);

    return `Summary of ${email.subject || "No subject"}":
    This is a test summary generated by the backend.
    The email was received from ${email.sender || "unknown sender"}.`;
};